### ISSUE TITLE
Can't set overflow-y: visible

### ISSUE THREAD

**Issue by jorosafi** [redacademy/b2w-winter-2018#1]
On the top image of the Process page, I need the hero image to overflow the top part of the div so it overlaps with the content above. I have tried setting overflow-y to visible and the inspect tools tell me the image is actually overflowing, but the image is not visible. 

Leaving here as a reminder to get back to this. 

@EricChan277 and @cchan54, if either of you have an idea of how to do this I would appreciate the help.

**Comment by EricChan277** [comment]
I got you fam 

Commit link : 2dfd6aff72469450a4a7f089c190c48df33dbafe
