### ISSUE TITLE
Contact Us - Could all that info just be in one WYSIWYG

### ISSUE THREAD

**Issue by rcass** [redacademy/b2w-winter-2018#10]
For this page, it would be easier if all that info was just in one WYSIWYG.

The contact form esp. does not need to be in it's own WYSIWYG, seems very redundant.

**Comment by jorosafi** [comment]
The reason I did it is the styling for mobile and desktop is substantially different. I couldn't make the different styling without wrapping each individual element inside a div. 

If I leave it all inside one wysiwyg, the client could easily break the styling by changing something inside the wysiwyg.

**Comment by jorosafi** [comment]
Desktop version: https://projects.invisionapp.com/share/PVG8L55Y4NR#/screens/283645921
Mobile: https://projects.invisionapp.com/share/YPG8ROPJWHF#/screens/283871750

**Comment by rcass** [comment]
Ahhhh that makes sense 👌 

Thanks for explaining that!
