### ISSUE TITLE
IIFE and doc ready

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/b2w-winter-2018#15]
You may not need to use both an IIFE and doc ready, instead you could just use something like...

```
jQuery(document).ready(function($){
  // your code here
});
```

https://github.com/redacademy/b2w-winter-2018/blob/923953b3f895ce5bbbf141b95c8f56a92db10e32/themes/b2w-theme/js/faq.js#L3

**Comment by jorosafi** [comment]
I changed this on the faq.js

@EricChan277 please add this to teh b2w-scripts when you are done working on the about page accordion.

**Comment by EricChan277** [comment]
Commit URL: https://github.com/redacademy/b2w-winter-2018/commit/98870b3c25b5af0bf8fdaaddd1fceeaddc2cdacc

Done.
