### ISSUE TITLE
CountItUp

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/b2w-winter-2018#16]
If this file is throwing errors when compiling you can move it from the js folder e.g. to a lib folder in the root directory. 
That way gulp wouldn't try to process the file when running gulp scripts

b2w-winter-2018/themes/b2w-theme/js/countUp.js

**Comment by EricChan277** [comment]
Commit link: 74e1b9b81cf50629791d3f07968b744aeb841fe5
