### ISSUE TITLE
window resize

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/b2w-winter-2018#17]
The window resize event can be useful however it can also fire events quite often. If you want to wrangle the events a bit you can try using setTimeout.

An excellent example can be found at: https://css-tricks.com/snippets/jquery/done-resizing-event/

https://github.com/redacademy/b2w-winter-2018/blob/923953b3f895ce5bbbf141b95c8f56a92db10e32/themes/b2w-theme/js/b2w-scripts.js#L5

**Comment by EricChan277** [comment]
Commit link: c1d3a71acd3d34356b46c45e628580e839e5707f
