### ISSUE TITLE
Console Errors 

### ISSUE THREAD

**Issue by rcass** [redacademy/b2w-winter-2018#3]
![screen shot 2018-03-26 at 1 27 38 pm](https://user-images.githubusercontent.com/5028555/37931124-8123af24-30f9-11e8-9cc4-9bedb46ca597.png)

Just make sure all the errors are resolved before this is client ready

**Comment by EricChan277** [comment]
I am unable to replicate this error

**Comment by rcass** [comment]
Ya i think when I saw the error you were still working on the count up js. So no worries 👍
