### ISSUE TITLE
About Page - Use Default WYSIWYG

### ISSUE THREAD

**Issue by rcass** [redacademy/b2w-winter-2018#6]
When ever possible, try using WordPress defaults such as the the default WYSIWYG editor. 

On the about page, there is really no need to the WYSIWYG custom field, instead you should just use the default editor.

Recommended, is removing the extra field.

If time is really an issue, to avoid confusion please hide the default WYSIWYG

**Comment by EricChan277** [comment]
http://b2w.van.cp.academy.red/wp-admin/post.php?post=8&action=edit
