### ISSUE TITLE
FAQ - Hide the default editor

### ISSUE THREAD

**Issue by rcass** [redacademy/b2w-winter-2018#8]
To avoid confusion, hide the default editor

**Comment by jorosafi** [comment]
Does it make sense to leave it there in case they want to add any content above the accordion? That was my thinking when I decided to leave it in place.

**Comment by rcass** [comment]
Ya that is okay then! 

Just make sure that you test adding content to that WYSIWYG and that it doesn't look broken on the front end

**Comment by rcass** [comment]
Okay just tested.

I just have one comment, I think the search area should stay with the FAQ accordions.

So basically call the_content() before the search area.
