### ISSUE TITLE
More of the Front Page should be available to the client

### ISSUE THREAD

**Issue by rcass** [redacademy/b2w-winter-2018#9]
Looking at the front-page.php, many of the content is hard coded into the php file.

Since this is content, the client will probably want to change/modify it in the future. So it is best if we make this content available.

Here are some suggestions:
**1) Use the default editor, maybe for this bit of content**
https://github.com/redacademy/b2w-winter-2018/blob/923953b3f895ce5bbbf141b95c8f56a92db10e32/themes/b2w-theme/front-page.php#L20-L22

**2) Services -> could be a set of custom fields:**
3 image and 3 text fields (just text field, not text area of WYSIWYG)

**3) Stats -> could be a set of custom fields:**
6 text fields (just text field, not text area of WYSIWYG)
But basically: 1 field for the top (white) & 1 for the bottom (purple text) X 3

**Comment by jorosafi** [comment]
@cchan54 can you do this tonight? If not I will get on this.
